"""baseline: full schema as of hit_gbm_v2 era

Revision ID: c8a75a27355e
Revises: 
Create Date: 2026-07-07 17:15:44.188168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a75a27355e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batter_game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('team', sa.String(length=50), nullable=True),
    sa.Column('game_date', sa.String(length=10), nullable=False),
    sa.Column('opponent', sa.String(length=50), nullable=True),
    sa.Column('at_bats', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('doubles', sa.Integer(), nullable=True),
    sa.Column('triples', sa.Integer(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('rbi', sa.Integer(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('stolen_bases', sa.Integer(), nullable=True),
    sa.Column('walks', sa.Integer(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('hit_by_pitch', sa.Integer(), nullable=True),
    sa.Column('sacrifice_flies', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggested_date', sa.String(length=10), nullable=False),
    sa.Column('generated_at', sa.String(length=30), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('player_mlb_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('player_team', sa.String(length=50), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('opposing_pitcher_mlb_id', sa.Integer(), nullable=True),
    sa.Column('opposing_pitcher_name', sa.String(length=100), nullable=True),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('game_time', sa.String(length=30), nullable=True),
    sa.Column('batting_order', sa.Integer(), nullable=True),
    sa.Column('lineup_source', sa.String(length=20), nullable=True),
    sa.Column('lineup_provider', sa.String(length=50), nullable=True),
    sa.Column('lineup_confirmed', sa.String(length=10), nullable=True),
    sa.Column('lineup_edge_threshold', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('signals_json', sa.String(length=2000), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('actual_at_bats', sa.Integer(), nullable=True),
    sa.Column('actual_hits', sa.Integer(), nullable=True),
    sa.Column('actual_doubles', sa.Integer(), nullable=True),
    sa.Column('actual_triples', sa.Integer(), nullable=True),
    sa.Column('actual_home_runs', sa.Integer(), nullable=True),
    sa.Column('actual_total_bases', sa.Integer(), nullable=True),
    sa.Column('actual_rbi', sa.Integer(), nullable=True),
    sa.Column('actual_runs', sa.Integer(), nullable=True),
    sa.Column('actual_walks', sa.Integer(), nullable=True),
    sa.Column('actual_strikeouts', sa.Integer(), nullable=True),
    sa.Column('actual_recorded_at', sa.String(length=30), nullable=True),
    sa.Column('actual_skip_reason', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('betting_odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=True),
    sa.Column('sportsbook', sa.String(length=100), nullable=False),
    sa.Column('market_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('over_odds', sa.Integer(), nullable=True),
    sa.Column('under_odds', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fantasy_leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('league_name', sa.String(length=200), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('scoring_settings', sa.String(length=5000), nullable=False),
    sa.Column('espn_s2', sa.String(length=500), nullable=True),
    sa.Column('swid', sa.String(length=100), nullable=True),
    sa.Column('yahoo_league_key', sa.String(length=50), nullable=True),
    sa.Column('yahoo_access_token', sa.String(length=2000), nullable=True),
    sa.Column('yahoo_refresh_token', sa.String(length=2000), nullable=True),
    sa.Column('yahoo_token_expires_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hit_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pick_date', sa.String(length=10), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('generated_at', sa.String(length=40), nullable=True),
    sa.Column('trained_on_rows', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=150), nullable=True),
    sa.Column('team', sa.String(length=60), nullable=True),
    sa.Column('opponent', sa.String(length=60), nullable=True),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('batting_order', sa.Integer(), nullable=True),
    sa.Column('bats', sa.String(length=2), nullable=True),
    sa.Column('pitcher_id', sa.Integer(), nullable=True),
    sa.Column('pitcher_name', sa.String(length=150), nullable=True),
    sa.Column('pitcher_throws', sa.String(length=2), nullable=True),
    sa.Column('lineup_source', sa.String(length=100), nullable=True),
    sa.Column('hit_probability', sa.Float(), nullable=True),
    sa.Column('season_hit_per_pa', sa.Float(), nullable=True),
    sa.Column('last10_hit_per_pa', sa.Float(), nullable=True),
    sa.Column('platoon_advantage', sa.Integer(), nullable=True),
    sa.Column('played', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('got_hit', sa.Integer(), nullable=True),
    sa.Column('graded_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hitter_prop_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_mlb_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(length=150), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=True),
    sa.Column('market_type', sa.String(length=50), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('no_vig_market_probability', sa.Float(), nullable=True),
    sa.Column('edge', sa.Float(), nullable=True),
    sa.Column('recommended_side', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hitter_savant_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_mlb_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('pa', sa.Integer(), nullable=False),
    sa.Column('xwoba', sa.Float(), nullable=True),
    sa.Column('woba', sa.Float(), nullable=True),
    sa.Column('xba', sa.Float(), nullable=True),
    sa.Column('xslg', sa.Float(), nullable=True),
    sa.Column('ba', sa.Float(), nullable=True),
    sa.Column('slg', sa.Float(), nullable=True),
    sa.Column('barrel_ct', sa.Integer(), nullable=True),
    sa.Column('hard_hit_ct', sa.Integer(), nullable=True),
    sa.Column('barrels_per_pa', sa.Float(), nullable=True),
    sa.Column('hard_hit_percent', sa.Float(), nullable=True),
    sa.Column('exit_velocity_avg', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitcher_game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('team', sa.String(length=50), nullable=True),
    sa.Column('game_date', sa.String(length=10), nullable=False),
    sa.Column('opponent', sa.String(length=50), nullable=True),
    sa.Column('innings_pitched', sa.Float(), nullable=True),
    sa.Column('hits_allowed', sa.Integer(), nullable=True),
    sa.Column('earned_runs', sa.Integer(), nullable=True),
    sa.Column('walks', sa.Integer(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('home_runs_allowed', sa.Integer(), nullable=True),
    sa.Column('hit_by_pitch', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('quality_start', sa.Integer(), nullable=True),
    sa.Column('pitches', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('team', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('whip', sa.Float(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('innings_pitched', sa.Float(), nullable=True),
    sa.Column('hits_allowed', sa.Integer(), nullable=True),
    sa.Column('earned_runs', sa.Integer(), nullable=True),
    sa.Column('walks', sa.Integer(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('home_runs_allowed', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('hit_by_pitch', sa.Integer(), nullable=True),
    sa.Column('quality_starts', sa.Integer(), nullable=True),
    sa.Column('mlb_id', sa.Integer(), nullable=True),
    sa.Column('throws', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('team', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('batting_average', sa.Float(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('rbi', sa.Integer(), nullable=True),
    sa.Column('stolen_bases', sa.Integer(), nullable=True),
    sa.Column('ops', sa.Float(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('total_bases', sa.Integer(), nullable=True),
    sa.Column('at_bats', sa.Integer(), nullable=True),
    sa.Column('walks', sa.Integer(), nullable=True),
    sa.Column('hit_by_pitch', sa.Integer(), nullable=True),
    sa.Column('sacrifice_flies', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('doubles', sa.Integer(), nullable=True),
    sa.Column('triples', sa.Integer(), nullable=True),
    sa.Column('caught_stealing', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('mlb_id', sa.Integer(), nullable=True),
    sa.Column('bats', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_metadata',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_metadata')
    op.drop_table('players')
    op.drop_table('pitchers')
    op.drop_table('pitcher_game_logs')
    op.drop_table('hitter_savant_snapshots')
    op.drop_table('hitter_prop_projections')
    op.drop_table('hit_picks')
    op.drop_table('fantasy_leagues')
    op.drop_table('betting_odds_snapshots')
    op.drop_table('bet_suggestions')
    op.drop_table('batter_game_logs')
    # ### end Alembic commands ###
